pom.xml, src/main/java/org/dcsa/core/events/controller/AbstractEventController.java
=> Removed swagger annotations and dependency

pom.xml
Part of issue : dcsaorg/DCSA-Core#79
=> Renamed dcsa.tag to dcsa.core.tag

src/main/java/org/dcsa/core/events/model/EquipmentEvent.java, src/main/java/org/dcsa/core/events/service/EquipmentEventService.java, src/main/java/org/dcsa/core/events/service/TransportCallService.java, src/main/java/org/dcsa/core/events/service/TransportEventService.java, src/main/java/org/dcsa/core/events/service/impl/EquipmentEventServiceImpl.java, src/main/java/org/dcsa/core/events/service/impl/GenericEventServiceImpl.java, src/main/java/org/dcsa/core/events/service/impl/ReferenceServiceImpl.java, src/main/java/org/dcsa/core/events/service/impl/TransportCallServiceImpl.java, src/main/java/org/dcsa/core/events/service/impl/TransportCallTOServiceImpl.java, src/main/java/org/dcsa/core/events/service/impl/TransportEventServiceImpl.java
=> Map in References, DocumentReferences and TransportCallTO on EquipmentEvent

pom.xml
=> Bump DCSA-Event-Core to 0.0.3

src/main/java/org/dcsa/core/events/model/ShipmentEvent.java, src/main/java/org/dcsa/core/events/model/base/AbstractFacility.java
Resolves:
https://dcsa.atlassian.net/browse/DDT-38
=> Sync changes for IM 3.2

pom.xml, src/main/java/org/dcsa/core/events/service/impl/TransportCallTOServiceImpl.java
=> Fix bug in TransportCallTOServiceImpl

src/main/java/org/dcsa/core/events/model/ShipmentEvent.java, src/main/java/org/dcsa/core/events/model/enums/DocumentReferenceType.java, src/main/java/org/dcsa/core/events/model/enums/EventClassifierCode.java, src/main/java/org/dcsa/core/events/repository/ReferenceRepository.java, src/main/java/org/dcsa/core/events/repository/ShipmentEventRepository.java, src/main/java/org/dcsa/core/events/service/ShipmentEventService.java, src/main/java/org/dcsa/core/events/service/impl/GenericEventServiceImpl.java, src/main/java/org/dcsa/core/events/service/impl/ShipmentEventServiceImpl.java
Resolves:
https://dcsa.atlassian.net/browse/DDT-28
=> Updated shipment event with document references and references

pom.xml, src/main/java/org/dcsa/core/events/config/MessageServiceConfig.java, src/main/java/org/dcsa/core/events/model/Event.java, src/main/java/org/dcsa/core/events/model/EventSubscriptionState.java, src/main/java/org/dcsa/core/events/model/Message.java, src/main/java/org/dcsa/core/events/model/PendingMessage.java, src/main/java/org/dcsa/core/events/model/SignatureFunction.java, src/main/java/org/dcsa/core/events/model/SignatureResult.java, src/main/java/org/dcsa/core/events/model/enums/SignatureMethod.java, src/main/java/org/dcsa/core/events/repository/PendingEventRepository.java, src/main/java/org/dcsa/core/events/service/impl/MessageSignatureHandler.java
=> DDT-14: Create a PendingMessage model for the subscription logic

src/main/java/org/dcsa/core/events/service/impl/GenericEventServiceImpl.java
Preserve order of events in GenericEventService.
=> GenericEventService: Fix order bug

src/main/java/org/dcsa/core/events/model/Address.java, src/main/java/org/dcsa/core/events/model/Carrier.java, src/main/java/org/dcsa/core/events/model/Vessel.java, src/main/java/org/dcsa/core/events/model/enums/CarrierCodeListProvider.java, src/main/java/org/dcsa/core/events/model/transferobjects/FacilityTO.java, src/main/java/org/dcsa/core/events/model/transferobjects/LocationTO.java, src/main/java/org/dcsa/core/events/model/transferobjects/TransportCallTO.java, src/main/java/org/dcsa/core/events/service/impl/TransportEventServiceImpl.java
This should conclude mapping of transport call into events.
=> DDT-24 Map transport call

pom.xml
=> Bump DCSA-Event-Core to 0.0.6-SNAPSHOT

pom.xml
=> Bump DCSA-Event-Core to 0.0.7-SNAPSHOT

src/main/java/org/dcsa/core/events/model/Event.java, src/main/java/org/dcsa/core/events/util/ExtendedGenericEventRequest.java
Resolves:
https://dcsa.atlassian.net/browse/DDT-32
**Note:** scheduleID is know issue and will be fixed later.
=> DDT-32 query fields

src/main/java/org/dcsa/core/events/model/Equipment.java, src/main/java/org/dcsa/core/events/model/EquipmentEvent.java, src/main/java/org/dcsa/core/events/model/ModeOfTransport.java, src/main/java/org/dcsa/core/events/model/Service.java, src/main/java/org/dcsa/core/events/model/Voyage.java, src/main/java/org/dcsa/core/events/model/transferobjects/TransportCallTO.java, src/main/java/org/dcsa/core/events/repository/EquipmentRepository.java, src/main/java/org/dcsa/core/events/repository/ModeOfTransportRepository.java, src/main/java/org/dcsa/core/events/repository/ServiceRepository.java, src/main/java/org/dcsa/core/events/repository/VoyageRepository.java, src/main/java/org/dcsa/core/events/service/impl/EquipmentEventServiceImpl.java, src/main/java/org/dcsa/core/events/service/impl/GenericEventServiceImpl.java, src/main/java/org/dcsa/core/events/service/impl/TransportCallTOServiceImpl.java, src/main/java/org/dcsa/core/events/util/ExtendedGenericEventRequest.java
Resolves:
https://dcsa.atlassian.net/browse/DDT-146
https://dcsa.atlassian.net/browse/DDT-149
https://dcsa.atlassian.net/browse/DDT-150
https://dcsa.atlassian.net/browse/DDT-167
=> Bug fixes DDT : 146, 149, 150

src/main/java/org/dcsa/core/events/model/OperationsEvent.java, src/main/java/org/dcsa/core/events/service/impl/OperationsEventServiceImpl.java
Issue: https://dcsa.atlassian.net/browse/DDT-208
=> DDT: 208 - Add missing fields in OperationsEvent

src/main/java/org/dcsa/core/events/model/OperationsEvent.java, src/main/java/org/dcsa/core/events/model/base/AbstractTransportCall.java, src/main/java/org/dcsa/core/events/model/enums/FacilityTypeCode.java
Add @EnumSubset validation to FacilityTypeCode in OperationsEvent and in TransportCall
=> DDT-213: Add a FacilityTypeCode enum

src/main/java/org/dcsa/core/events/repository/CarrierRepository.java, src/main/java/org/dcsa/core/events/service/CarrierService.java, src/main/java/org/dcsa/core/events/service/TransportCallTOService.java, src/main/java/org/dcsa/core/events/service/impl/CarrierServiceImpl.java, src/main/java/org/dcsa/core/events/service/impl/TransportCallTOServiceImpl.java, src/main/java/org/dcsa/core/events/service/impl/VesselServiceImpl.java
Relates to DDT-17-unofficial-APIs in OVS 
- The CarrierRepo is moved to Event-Core to allow for use in VesselServiceImp
- Carrier attribute is populated
=> DDT-17-unofficial-APIs

src/main/java/org/dcsa/core/events/repository/CarrierRepository.java, src/main/java/org/dcsa/core/events/service/impl/CarrierServiceImpl.java, src/main/java/org/dcsa/core/events/service/impl/VesselServiceImpl.java
=> VesselService: Reject invalid vessel IMO in findById

pom.xml
=> Bump DCSA-Event-Core to 0.0.14

pom.xml, src/main/java/org/dcsa/core/events/model/TransportCallVoyage.java
Variable names were incorrect according to the IM.
=> Fix transport call voyage

src/main/java/org/dcsa/core/events/model/SignatureFunction.java, src/main/java/org/dcsa/core/events/service/impl/MessageSignatureHandler.java
=> Correct signature header value

src/main/java/org/dcsa/core/events/repository/EventSubscriptionRepository.java, src/main/java/org/dcsa/core/events/service/impl/EventSubscriptionServiceImpl.java
=> HACK: fix crash on empty lists in EventSubscription

src/main/java/org/dcsa/core/events/service/impl/MessageSignatureHandler.java
=> Fix mapping pending events

pom.xml
=> Bump DCSA-Event-Core to 0.0.18

src/main/java/org/dcsa/core/events/service/impl/MessageSignatureHandler.java, src/main/java/org/dcsa/core/events/service/impl/PendingEventServiceImpl.java
=> Improve error handling for emitting messages

src/main/java/org/dcsa/core/events/repository/TransportCallRepository.java, src/main/java/org/dcsa/core/events/util/ExtendedGenericEventRequest.java
=> Update queries to cope with vessel IMO move

src/main/java/org/dcsa/core/events/model/OperationsEvent.java
=> Add missing `@JsonIgnore`

pom.xml
=> Bump DCSA-Event-Core to 0.0.19

src/main/java/org/dcsa/core/events/service/impl/TransportCallTOServiceImpl.java
=> TransportCallTOService.create: Ensure carrier is set on vessel

src/main/java/org/dcsa/core/events/service/impl/TransportCallTOServiceImpl.java
To populate both CarrierVoyageNumber and CarrierServiceCode in TransportCall
=> findAllExtended override for TransportCallTOServiceImpl

src/main/java/org/dcsa/core/events/service/impl/TransportCallTOServiceImpl.java
Needed for https://github.com/dcsaorg/DCSA-OVS/pull/45
=> DDT-292 Set new vessel for transportCallTO

src/main/java/org/dcsa/core/events/service/impl/GenericEventServiceImpl.java
=> GenericEventService: Make some fields visible for subclasses

src/main/java/org/dcsa/core/events/util/ExtendedGenericEventRequest.java
=> ExtendedGenericEventRequest: Fix bugs related to OperationsEvent and transport calls

src/main/java/org/dcsa/core/events/model/base/AbstractFacility.java, src/main/java/org/dcsa/core/events/model/transferobjects/TransportCallTO.java
=> Fix typo of SMDG in entity

pom.xml
=> Bump DCSA-Event-Core to 0.0.21

src/main/java/org/dcsa/core/events/model/OperationsEvent.java
=> Fix timestamp type name for ATS Pilotage

src/main/java/org/dcsa/core/events/model/enums/SignatureMethod.java
=> Permit secrets between 32 and 64 bytes

src/main/java/org/dcsa/core/events/model/Location.java, src/main/java/org/dcsa/core/events/model/OperationsEvent.java, src/main/java/org/dcsa/core/events/model/base/AbstractLocation.java, src/main/java/org/dcsa/core/events/model/enums/PortCallServiceTypeCode.java, src/main/java/org/dcsa/core/events/model/transferobjects/FacilityTO.java, src/main/java/org/dcsa/core/events/model/transferobjects/LocationTO.java, src/main/java/org/dcsa/core/events/repository/LocationRepository.java, src/main/java/org/dcsa/core/events/service/impl/LocationServiceImpl.java
... Also include some of the new JIT 1.1 timestamps
=> DDT-392: Move facility to location

pom.xml, src/main/java/org/dcsa/core/events/model/enums/SignatureMethod.java, src/main/java/org/dcsa/core/events/service/impl/TransportCallTOServiceImpl.java, src/main/java/org/dcsa/core/events/service/impl/VesselServiceImpl.java
=> DDT-392: Support creating timestamps without knowing the carrier of the vessel

src/main/java/org/dcsa/core/events/model/base/AbstractFacility.java
=> Fix facilitySMDGCode length

pom.xml, src/main/java/org/dcsa/core/events/model/transferobjects/LocationTO.java, src/main/java/org/dcsa/core/events/model/transferobjects/TransportCallTO.java
=> Correctly show UN Locodes for TransportCallTO instances

pom.xml, src/main/java/org/dcsa/core/events/model/OperationsEvent.java
- This was prompted by issue [DDT-519](https://dcsa.atlassian.net/browse/DDT-519)
- As this logic is needed in OVS-notifications.
=> Move ensurePhaseTypeIsDefined logic to OperationsEvent

pom.xml, src/main/java/org/dcsa/core/events/repository/TimestampDefinitionRepository.java
A Query is created to support extraction timestamp type name for issue DDT-520
=> DDT-520-Allow for extraction of timestamp definition using EventID

pom.xml, src/main/java/org/dcsa/core/events/service/impl/OperationsEventServiceImpl.java
=> Fix create OPS event bug

src/main/java/org/dcsa/core/events/service/impl/EventSubscriptionTOServiceImpl.java
=> EventSubscriptionTOServiceImpl: Implement `findAllExtended` correctly

src/main/java/org/dcsa/core/events/repository/BookingRepository.java, src/main/java/org/dcsa/core/events/repository/VesselRepository.java
added repositories needed for Booking request summaries
=> Ddt 555 booking request summaries

src/main/java/org/dcsa/core/events/model/enums/DocumentStatus.java, src/main/java/org/dcsa/core/events/model/enums/ShipmentEventTypeCode.java, src/test/java/org/dcsa/core/events/repository/impl/BookingCustomRepositoryImplTest.java
Resolves https://dcsa.atlassian.net/browse/DDT-612
=> DDT-612 limited statusses in documentStatus

src/main/java/org/dcsa/core/events/model/enums/DocumentTypeCode.java
=> DDT-633 added missing document types codes to enum

src/main/java/org/dcsa/core/events/model/Shipment.java, src/main/java/org/dcsa/core/events/repository/ShipmentCustomRepository.java, src/main/java/org/dcsa/core/events/repository/impl/ShipmentCustomRepositoryImpl.java, src/test/java/org/dcsa/core/events/repository/impl/ShipmentCustomRepositoryImplTest.java
resolves: DDT-673
depends on: https://github.com/dcsaorg/DCSA-Event-Core/pull/171
=> Ddt 673 added created updated datetime to shipment

src/main/java/org/dcsa/core/events/model/Shipment.java, src/main/java/org/dcsa/core/events/repository/BookingCustomRepository.java, src/main/java/org/dcsa/core/events/repository/ShipmentCustomRepository.java, src/main/java/org/dcsa/core/events/repository/ShipmentRepository.java, src/main/java/org/dcsa/core/events/repository/impl/BookingCustomRepositoryImpl.java, src/main/java/org/dcsa/core/events/repository/impl/ShipmentCustomRepositoryImpl.java, src/test/java/org/dcsa/core/events/repository/impl/ShipmentCustomRepositoryImplTest.java
Adds queries used for pagination as well as fixes order by clauses spread over two tables by consolidating two queries into one
=> Pagination

pom.xml, src/main/java/org/dcsa/core/events/model/Booking.java, src/main/java/org/dcsa/core/events/model/PartyContactDetails.java, src/main/java/org/dcsa/core/events/model/transferobjects/DocumentPartyTO.java, src/main/java/org/dcsa/core/events/model/transferobjects/PartyContactDetailsTO.java, src/main/java/org/dcsa/core/events/service/DocumentPartyService.java, src/main/java/org/dcsa/core/events/service/PartyService.java, src/main/java/org/dcsa/core/events/service/impl/DocumentPartyServiceImpl.java, src/main/java/org/dcsa/core/events/validator/ValidLocationSubtype.java, src/main/java/org/dcsa/core/events/validator/ValidLocationSubtypeValidator.java, src/test/java/org/dcsa/core/events/service/impl/DocumentPartyServiceImplTest.java, src/test/java/org/dcsa/core/events/validator/ValidLocationSubtypeValidatorTest.java
=> Ddt 762 insert document parties

src/main/java/org/dcsa/core/events/model/transferobjects/ReferenceTO.java, src/main/java/org/dcsa/core/events/repository/ReferenceRepository.java, src/main/java/org/dcsa/core/events/service/ReferenceService.java, src/main/java/org/dcsa/core/events/service/impl/ReferenceServiceImpl.java, src/test/java/org/dcsa/core/events/service/impl/ReferenceServiceImplTest.java
Taken from Booking and added shippingInstructionID parameter
=> DDT-763: Logic to insert reference

src/main/java/org/dcsa/core/events/model/enums/ColumnReferenceType.java, src/main/java/org/dcsa/core/events/model/mapper/PartyMapper.java, src/main/java/org/dcsa/core/events/repository/DocumentPartyRepository.java, src/main/java/org/dcsa/core/events/service/DocumentPartyService.java, src/main/java/org/dcsa/core/events/service/impl/DocumentPartyServiceImpl.java, src/test/java/org/dcsa/core/events/service/impl/DocumentPartyServiceImplTest.java
Resolves:
https://dcsa.atlassian.net/browse/DDT-793
=> Added logic to fetch document parties

src/main/java/org/dcsa/core/events/model/Seal.java, src/main/java/org/dcsa/core/events/model/ShipmentEquipment.java, src/main/java/org/dcsa/core/events/model/mapper/ShipmentEquipmentMapper.java
SealMapper did not set ShipmentEquipmentID
=> ShipmentEquipment and Seal according to IM

src/main/java/org/dcsa/core/events/model/CargoItem.java, src/main/java/org/dcsa/core/events/model/CargoLineItem.java, src/main/java/org/dcsa/core/events/model/Seal.java, src/main/java/org/dcsa/core/events/model/mapper/CargoItemMapper.java, src/main/java/org/dcsa/core/events/model/mapper/EquipmentMapper.java, src/main/java/org/dcsa/core/events/repository/CargoItemCustomRepository.java, src/main/java/org/dcsa/core/events/repository/CargoItemRepository.java, src/main/java/org/dcsa/core/events/repository/ReferenceRepository.java, src/main/java/org/dcsa/core/events/repository/ShipmentEquipmentCustomRepository.java, src/main/java/org/dcsa/core/events/repository/ShipmentEquipmentRepository.java, src/main/java/org/dcsa/core/events/repository/impl/CargoItemCustomRepositoryImpl.java, src/main/java/org/dcsa/core/events/repository/impl/ShipmentEquipmentCustomRepositoryImpl.java, src/main/java/org/dcsa/core/events/service/ReferenceService.java, src/main/java/org/dcsa/core/events/service/ShipmentEquipmentService.java, src/main/java/org/dcsa/core/events/service/impl/ReferenceServiceImpl.java, src/main/java/org/dcsa/core/events/service/impl/ShipmentEquipmentServiceImpl.java, src/test/java/org/dcsa/core/events/repository/impl/CargoItemCustomRepositoryImplTest.java, src/test/java/org/dcsa/core/events/repository/impl/ShipmentEquipmentCustomRepositoryImplTest.java, src/test/java/org/dcsa/core/events/service/impl/ShipmentEquipmentServiceImplTest.java
=> DDT-800 fetch utilized transport equipment

src/main/java/org/dcsa/core/events/service/impl/EquipmentEventServiceImpl.java, src/main/java/org/dcsa/core/events/service/impl/OperationsEventServiceImpl.java, src/main/java/org/dcsa/core/events/service/impl/ShipmentEventServiceImpl.java, src/main/java/org/dcsa/core/events/service/impl/TransportEventServiceImpl.java, src/main/java/org/dcsa/core/events/util/ExtendedGenericEventRequest.java
To match https://github.com/dcsaorg/DCSA-Core/pull/139 (needs a "lock-step" merge).
=> Tweaks to DCSA-Event-Core to match DCSA-Core

src/main/java/org/dcsa/core/events/service/AbstractTransportCallTOService.java, src/main/java/org/dcsa/core/events/service/AddressService.java, src/main/java/org/dcsa/core/events/service/EventService.java, src/main/java/org/dcsa/core/events/service/EventSubscriptionService.java, src/main/java/org/dcsa/core/events/service/FacilityService.java, src/main/java/org/dcsa/core/events/service/LocationService.java, src/main/java/org/dcsa/core/events/service/PendingEventService.java, src/main/java/org/dcsa/core/events/service/ServiceService.java, src/main/java/org/dcsa/core/events/service/TimestampDefinitionService.java, src/main/java/org/dcsa/core/events/service/VesselService.java, src/main/java/org/dcsa/core/events/service/VoyageService.java, src/main/java/org/dcsa/core/events/service/impl/AbstractTransportCallTOServiceImpl.java, src/main/java/org/dcsa/core/events/service/impl/EquipmentEventServiceImpl.java, src/main/java/org/dcsa/core/events/service/impl/EventSubscriptionServiceImpl.java, src/main/java/org/dcsa/core/events/service/impl/FacilityServiceImpl.java, src/main/java/org/dcsa/core/events/service/impl/OperationsEventServiceImpl.java, src/main/java/org/dcsa/core/events/service/impl/ServiceServiceImpl.java, src/main/java/org/dcsa/core/events/service/impl/ShipmentEventServiceImpl.java, src/main/java/org/dcsa/core/events/service/impl/TimestampDefinitionServiceImpl.java, src/main/java/org/dcsa/core/events/service/impl/TransportEventServiceImpl.java, src/main/java/org/dcsa/core/events/service/impl/VesselServiceImpl.java, src/main/java/org/dcsa/core/events/service/impl/VoyageServiceImpl.java
To match the recent renaming in DCSA-Core
=> Migrate classes to the new QueryService names

src/main/java/org/dcsa/core/events/util/ExtendedGenericEventRequest.java
Change the method call into another similar method as the original is
about to be removed.
=> ExtendedGenericEventRequest: Update call

src/main/java/org/dcsa/core/events/model/AbstractTransportDocument.java
=> DDT-860 aligned TransportDocument entity with IM and TO

src/main/java/org/dcsa/core/events/model/AbstractTransportDocument.java
=> DDT-860 fixed reference to carrier id as issuer in transport document

src/main/java/org/dcsa/core/events/model/CargoItem.java, src/test/java/org/dcsa/core/events/service/impl/ShipmentEquipmentServiceImplTest.java
=> DDT-812 [2/2]: Remove shipmentID from CargoItem

src/main/java/org/dcsa/core/events/repository/BookingRepository.java, src/main/java/org/dcsa/core/events/repository/ReferenceRepository.java, src/main/java/org/dcsa/core/events/repository/ServiceRepository.java, src/main/java/org/dcsa/core/events/repository/ShipmentEquipmentRepository.java, src/main/java/org/dcsa/core/events/repository/TransportRepository.java, src/main/java/org/dcsa/core/events/repository/VoyageRepository.java, src/test/java/org/dcsa/core/events/repository/impl/CargoItemCustomRepositoryImplTest.java
=> DDT-812: Fix some left over shipment ID usages

src/main/java/org/dcsa/core/events/model/transferobjects/ShipmentEquipmentTO.java, src/main/java/org/dcsa/core/events/model/transferobjects/ShippingInstructionTO.java
=> DDT-868: CargoItem and ShipmentEquipment is required on SI

src/main/java/org/dcsa/core/events/model/enums/DocumentTypeCode.java
=> Align EBL_DOCUMENT_TYPE_CODES with swagger

src/main/java/org/dcsa/core/events/repository/BookingRepository.java
based on shippingInstructionID and carrierBookingReference
=> DDT-882: Queries to fetch Bookings

src/main/java/org/dcsa/core/events/model/enums/ShipmentEventTypeCode.java
=> PENC is a valid doc status for eBL

src/main/java/org/dcsa/core/events/model/AbstractShipmentEquipment.java
=> DDT-918 isShipperOwned is required

src/main/java/org/dcsa/core/events/model/base/AbstractShippingInstruction.java
ReadOnly added to documentStatus, created and updated fields.
=> DDT-862: Ensure ReadOnly on fields

src/main/java/org/dcsa/core/events/model/enums/ShipmentEventTypeCode.java
=> DDT-962: eBL no longer uses PENC

src/main/java/org/dcsa/core/events/model/base/AbstractShippingInstruction.java
=> DDT-965: Add amendmentToTransportDocument on SI

pom.xml, src/main/java/org/dcsa/core/events/util/ExtendedGenericEventRequest.java, src/test/java/org/dcsa/core/events/repository/impl/ShipmentCustomRepositoryImplTest.java
=> DDT-929 [1/?]: Update spring boot to 2.6.4

pom.xml
=> Bump DCSA-Event-Core version to 0.0.58

pom.xml, src/main/java/org/dcsa/core/events/model/Event.java, src/main/java/org/dcsa/core/events/model/EventCarrierBookingReference.java, src/main/java/org/dcsa/core/events/service/impl/GenericEventServiceImpl.java, src/main/java/org/dcsa/core/events/util/ExtendedGenericEventRequest.java
Needs to go together with:
- https://github.com/dcsaorg/DCSA-Core/pull/159
- https://github.com/dcsaorg/DCSA-Information-Model/pull/240
=> DDT-929: Use the new events view for carrier booking refs

src/main/java/org/dcsa/core/events/repository/impl/CargoItemCustomRepositoryImpl.java, src/main/java/org/dcsa/core/events/repository/impl/ShipmentEquipmentCustomRepositoryImpl.java, src/test/java/org/dcsa/core/events/repository/impl/ShipmentEquipmentCustomRepositoryImplTest.java
=> bug/ Map shipmentEquipmentID correctly & fix test

src/main/java/org/dcsa/core/events/util/ExtendedGenericEventRequest.java
DDT-878 needs a test for `carrierBookingRequestReference` but the `GET
/events` endpoints do not support that at all.  With this commit, we
implement it.
=> Part of DDT-878: Support querying for carrierBookingRequestReference

pom.xml, src/main/java/org/dcsa/core/events/util/ExtendedGenericEventRequest.java
Depends on https://github.com/dcsaorg/DCSA-Core/pull/161
=> DDT-1004 [1/2]: Support voyage number filters

src/main/java/org/dcsa/core/events/model/UtilizedTransportEquipment.java, src/main/java/org/dcsa/core/events/model/mapper/UtilizedTransportEquipmentMapper.java, src/main/java/org/dcsa/core/events/repository/ReferenceRepository.java, src/main/java/org/dcsa/core/events/repository/UtilizedTransportEquipmentRepository.java, src/main/java/org/dcsa/core/events/service/impl/UtilizedTransportEquipmentServiceImpl.java, src/test/java/org/dcsa/core/events/maper/UtilizedTransportEquipmentMapperTest.java, src/test/java/org/dcsa/core/events/service/impl/ConsignmentItemServiceImplTest.java, src/test/java/org/dcsa/core/events/service/impl/UtilizedTransportEquipmentServiceImplTest.java
=> DDT-960 changes services and repositories to reflect IM changes

src/main/java/org/dcsa/core/events/model/ShipmentEvent.java, src/main/java/org/dcsa/core/events/model/enums/DocumentReferenceType.java, src/main/java/org/dcsa/core/events/repository/DocumentReferenceRepository.java, src/main/java/org/dcsa/core/events/repository/TransportCallRepository.java, src/main/java/org/dcsa/core/events/service/DocumentReferenceService.java, src/main/java/org/dcsa/core/events/service/TransportCallService.java, src/main/java/org/dcsa/core/events/service/impl/DocumentReferenceServiceImpl.java, src/main/java/org/dcsa/core/events/service/impl/EquipmentEventServiceImpl.java, src/main/java/org/dcsa/core/events/service/impl/ShipmentEventServiceImpl.java, src/main/java/org/dcsa/core/events/service/impl/TransportCallServiceImpl.java, src/main/java/org/dcsa/core/events/service/impl/TransportEventServiceImpl.java, src/main/java/org/dcsa/core/events/util/ExtendedGenericEventRequest.java
=> DDT-928: Rewrite how documentReferences are handled

src/main/java/org/dcsa/core/events/controller/AbstractEventController.java, src/main/java/org/dcsa/core/events/controller/AbstractEventSubscriptionController.java, src/main/java/org/dcsa/core/events/service/impl/EventSubscriptionServiceImpl.java
=> Migrate some exceptions to ConcreteRequestErrorMessageException

src/main/java/org/dcsa/core/events/edocumentation/model/transferobject/RequestedEquipmentTO.java, src/main/java/org/dcsa/core/events/model/RequestedEquipmentEquipment.java, src/main/java/org/dcsa/core/events/model/mapper/RequestedEquipmentMapper.java, src/main/java/org/dcsa/core/events/repository/RequestedEquipmentEquipmentRepository.java
Dependent on: https://github.com/dcsaorg/DCSA-Information-Model/pull/253
=> DDT-991: RequestedEquipmentEquipment

src/main/java/org/dcsa/core/events/edocumentation/service/ShipmentService.java, src/main/java/org/dcsa/core/events/edocumentation/service/impl/ShipmentServiceImpl.java
=> Refactor to make the code a bit easier to understand/less confusing

src/main/java/org/dcsa/core/events/repository/BookingRepository.java, src/main/java/org/dcsa/core/events/repository/ShipmentRepository.java
Resolves the event-core part of DDT-957
=> DDT-957 added query to retrieve active shipments and bookings

.github/workflows/checkDevPR.yml, pom.xml, src/main/java/org/dcsa/core/events/util/ExtendedGenericEventRequest.java
Part of the DDT-1015 changes.
Depends on https://github.com/dcsaorg/DCSA-Core/pull/168
=> Update DCSA-Event-Core to cope with DCSA-Core changes

src/main/java/org/dcsa/core/events/model/enums/DocumentTypeCode.java
=> DocumentTypeCode: Add BKG_DOCUMENT_TYPE_CODES

src/main/java/org/dcsa/core/events/repository/TransportDocumentRepository.java
=> DDT-953: Ensure GET SI/TD by reference returns correct errors

src/main/java/org/dcsa/core/events/edocumentation/repository/CarrierClauseRepository.java, src/main/java/org/dcsa/core/events/edocumentation/service/CarrierClauseService.java, src/main/java/org/dcsa/core/events/edocumentation/service/impl/CarrierClauseServiceImpl.java, src/main/java/org/dcsa/core/events/model/ShipmentCarrierClause.java, src/test/java/org/dcsa/core/events/edocumentation/service/impl/CarrierClauseServiceImplTest.java, src/test/java/org/dcsa/core/events/edocumentation/service/impl/ShipmentServiceImplTest.java
transport_document_reference changed to transport_document_id
=> ShipmentCarrierClauses.TDR -> TDID

src/main/java/org/dcsa/core/events/util/ExtendedGenericEventRequest.java
The method was not being called anymore. Since it was never called, we
can also remove some of the static initialization code setting up
public static final fields.
=> Remove unused code

src/main/java/org/dcsa/core/events/edocumentation/model/mapper/ShipmentEventMapper.java, src/main/java/org/dcsa/core/events/model/Booking.java
introduce shipmentEventMapper to use instead of the helper methods in BKG and moved check methods to Booking entity
=> introduced shipmentEventMapper and added check methods to Booking entity

src/main/java/org/dcsa/core/events/edocumentation/service/TransportService.java, src/main/java/org/dcsa/core/events/edocumentation/service/impl/TransportServiceImpl.java, src/test/java/org/dcsa/core/events/edocumentation/service/impl/TransportServiceImplTest.java
resolves: DDT-1039 (event_core part)
=> DDT-1039 added findTransportByShipmentID to transportService

src/main/java/org/dcsa/core/events/model/AbstractTransportDocument.java
=> Align names with Swagger spec

src/main/java/org/dcsa/core/events/model/TimestampDefinition.java, src/main/java/org/dcsa/core/events/repository/TimestampDefinitionRepository.java, src/main/java/org/dcsa/core/events/service/impl/TimestampDefinitionServiceImpl.java
=> Part of DDT-1050: Rewrite JIT timestamp matching code

src/main/java/org/dcsa/core/events/repository/BookingRepository.java, src/main/java/org/dcsa/core/events/repository/ShipmentRepository.java, src/main/java/org/dcsa/core/events/repository/TransportCallRepository.java, src/main/java/org/dcsa/core/events/repository/TransportDocumentTypeRepository.java, src/main/java/org/dcsa/core/events/service/impl/EventSubscriptionServiceImpl.java
=> Update some custom queries to be valid again

src/main/java/org/dcsa/core/events/repository/TransportCallRepository.java, src/main/java/org/dcsa/core/events/service/TransportCallService.java, src/main/java/org/dcsa/core/events/service/impl/TransportCallServiceImpl.java
=> DDT-1048: Terminal Call based Transport Calls

.github/workflows/publishRelease.yml, pom.xml
=> Prepare for release

pom.xml
=> Bump super pom version as well
